import { normalizeRoleValue, ROLE_VALUES } from "@/constants/roles";

const APPROVAL_ACCESS_ROLES = [
  ROLE_VALUES.LECTURER,
  ROLE_VALUES.ADMIN,
  ROLE_VALUES.SUPER_ADMINISTRATOR,
] as const;

const REQUESTER_ACCESS_ROLES = [
  ROLE_VALUES.STUDENT,
  ROLE_VALUES.LECTURER,
  ROLE_VALUES.STAFF,
  ROLE_VALUES.GUEST,
  ROLE_VALUES.ADMIN,
  ROLE_VALUES.SUPER_ADMINISTRATOR,
] as const;

const SAMPLE_TESTING_REQUESTER_ACCESS_ROLES = [
  ROLE_VALUES.STUDENT,
  ROLE_VALUES.STAFF,
  ROLE_VALUES.GUEST,
  ROLE_VALUES.LECTURER,
  ROLE_VALUES.ADMIN,
  ROLE_VALUES.SUPER_ADMINISTRATOR,
] as const;

const SAMPLE_TESTING_APPROVAL_ACCESS_ROLES = [
  ROLE_VALUES.ADMIN,
  ROLE_VALUES.SUPER_ADMINISTRATOR,
] as const;

const LAB_CLEARANCE_REQUESTER_ACCESS_ROLES = [
  ROLE_VALUES.STUDENT,
  ROLE_VALUES.ADMIN,
  ROLE_VALUES.SUPER_ADMINISTRATOR,
] as const;

const LAB_CLEARANCE_APPROVAL_ACCESS_ROLES = [
  ROLE_VALUES.ADMIN,
  ROLE_VALUES.SUPER_ADMINISTRATOR,
] as const;

const CATALOG_ACCESS_ROLES = [
  ROLE_VALUES.STUDENT,
  ROLE_VALUES.GUEST,
  ROLE_VALUES.LECTURER,
  ROLE_VALUES.STAFF,
  ROLE_VALUES.ADMIN,
  ROLE_VALUES.SUPER_ADMINISTRATOR,
] as const;

function isApprovalOnlyRole(role: string | null | undefined) {
  const normalizedRole = normalizeRoleValue(role);
  return normalizedRole === ROLE_VALUES.LECTURER;
}

export {
  APPROVAL_ACCESS_ROLES,
  REQUESTER_ACCESS_ROLES,
  SAMPLE_TESTING_REQUESTER_ACCESS_ROLES,
  SAMPLE_TESTING_APPROVAL_ACCESS_ROLES,
  LAB_CLEARANCE_REQUESTER_ACCESS_ROLES,
  LAB_CLEARANCE_APPROVAL_ACCESS_ROLES,
  CATALOG_ACCESS_ROLES,
  isApprovalOnlyRole,
};
