version: "3.9"

services:
  backend:
    build:
      context: ./backend
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend-react
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: postgres13
    restart: unless-stopped
    environment:
      POSTGRES_DB: csluse_db
      POSTGRES_USER: csluser
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
