const API_BASE_URL: string = (
  import.meta.env.VITE_API_BASE_URL || "http://localhost:8000/api"
).replace(/\/+$/, "");

// REGION: Auth API Endpoints
const API_AUTH_BASE = `${API_BASE_URL}/auth`;
const API_ADMIN_BASE = `${API_BASE_URL}/admin`;

const API_AUTH_LOGIN = `${API_AUTH_BASE}/login/`;
const API_AUTH_LOGIN_ROUTE = `${API_AUTH_BASE}/login/route/`;
const API_AUTH_LOGOUT = `${API_AUTH_BASE}/logout/`;
const API_AUTH_LOGIN_GOOGLE = `${API_AUTH_BASE}/oauth/google/login/`;
const API_AUTH_REGISTER = `${API_AUTH_BASE}/registration/`;
const API_AUTH_VERIFY_EMAIL = `${API_AUTH_BASE}/registration/verify-email/`;
const API_AUTH_EMAIL_STATUS = `${API_AUTH_BASE}/registration/check-email/`;
const API_AUTH_RESEND_VERIFICATION = `${API_AUTH_BASE}/registration/resend-email/`;
const API_AUTH_PASSWORD_RESET = `${API_AUTH_BASE}/password/reset/`;
const API_AUTH_PASSWORD_RESET_CONFIRM = `${API_AUTH_BASE}/password/reset/confirm/`;
const API_AUTH_PASSWORD_CHANGE = `${API_AUTH_BASE}/password/change/`;
const API_AUTH_TOKEN_REFRESH = `${API_AUTH_BASE}/token/refresh/`;
const API_AUTH_TOKEN_VERIFY = `${API_AUTH_BASE}/token/verify/`;

// REGION: User Profile API Endpoints
const API_AUTH_USER = `${API_AUTH_BASE}/user/`;
const API_AUTH_USER_PROFILE = `${API_AUTH_BASE}/user/profile/`;
const API_AUTH_MENTOR_USERS_DROPDOWN = `${API_AUTH_USER_PROFILE}mentor-dropdown/`;
const API_AUTH_USER_PROFILE_DETAIL = (id: string | number) =>
  `${API_AUTH_USER_PROFILE}${id}/`;

// REGION: Admin Profile API Endpoints
const API_AUTH_ADMIN_PROFILE = `${API_ADMIN_BASE}/profile/`;
const API_AUTH_ADMIN_PROFILE_DETAIL = (id: string | number) =>
  `${API_AUTH_ADMIN_PROFILE}${id}/`;
const API_AUTH_USERS = `${API_ADMIN_BASE}/users/`;
const API_AUTH_USERS_EXPORT = `${API_AUTH_USERS}export/`;
const API_AUTH_USERS_BULK_DELETE = `${API_AUTH_USERS}bulk-delete/`;
const API_AUTH_PIC_USERS = `${API_ADMIN_BASE}/pic-users/`;
const API_AUTH_PIC_USERS_DROPDOWN = `${API_AUTH_PIC_USERS}dropdown/`;
const API_AUTH_ASSIGNED_PIC_USERS_DROPDOWN = `${API_AUTH_PIC_USERS}assigned-dropdown/`;
const API_AUTH_PIC_USERS_BULK_REMOVE_ASSIGNMENTS = `${API_AUTH_PIC_USERS}bulk-remove-assignments/`;
const API_AUTH_PIC_USER_REMOVE_ASSIGNMENTS = (id: string | number) =>
  `${API_AUTH_PIC_USERS}${id}/remove-assignments/`;
const API_AUTH_ADMIN_ACTIONS = `${API_ADMIN_BASE}/actions/`;
const API_AUTH_ADMIN_ACTIONS_RECENT = `${API_AUTH_ADMIN_ACTIONS}recent/`;
const API_AUTH_ADMIN_ACTIONS_MY = `${API_AUTH_ADMIN_ACTIONS}my/`;
const API_AUTH_ADMIN_DASHBOARD = `${API_ADMIN_BASE}/dashboard/`;
const API_AUTH_ADMIN_DASHBOARD_KPIS = `${API_AUTH_ADMIN_DASHBOARD}kpis/`;

// REGION: Lab Clearance API Endpoints
const API_LAB_CLEARANCE = `${API_ADMIN_BASE}/lab-clearance/`;
const API_LAB_CLEARANCE_CHECK = `${API_LAB_CLEARANCE}check/`;

// REGION: Bookings API Endpoints
const API_BOOKINGS = `${API_BASE_URL}/bookings/`;
const API_BOOKINGS_MY = `${API_BOOKINGS}my/`;
const API_BOOKINGS_ALL = `${API_BOOKINGS}all/`;
const API_BOOKINGS_ALL_EXPORT = `${API_BOOKINGS}all/export/`;
const API_BOOKINGS_ALL_REQUESTERS = `${API_BOOKINGS}all/requesters/`;
const API_BOOKINGS_BULK_DELETE = `${API_BOOKINGS}bulk-delete/`;
const API_BOOKING_DETAIL = (id: string | number) => `${API_BOOKINGS}${id}/`;
const API_BOOKING_APPROVE = (id: string | number) =>
  `${API_BOOKINGS}${id}/approve/`;
const API_BOOKING_REJECT = (id: string | number) =>
  `${API_BOOKINGS}${id}/reject/`;
const API_BOOKING_COMPLETE = (id: string | number) =>
  `${API_BOOKINGS}${id}/complete/`;
const API_BOOKING_CANCEL = (id: string | number) =>
  `${API_BOOKINGS}${id}/cancel/`;
const API_BOOKING_REVIEW_CHECK = (id: string | number) =>
  `${API_BOOKINGS}${id}/review-check/`;
const API_BOOKINGS_BY_MONTH = `${API_BOOKINGS}by-month/`;

// REGION: Borrows API Endpoints
const API_BORROWS = `${API_BASE_URL}/borrows/`;
const API_BORROWS_MY = `${API_BORROWS}my/`;
const API_BORROWS_ALL = `${API_BORROWS}all/`;
const API_BORROWS_EXPORT = `${API_BORROWS}all/export/`;
const API_BORROWS_ALL_REQUESTERS = `${API_BORROWS}all/requesters/`;
const API_BORROWS_BULK_DELETE = `${API_BORROWS}bulk-delete/`;
const API_BORROW_DETAIL = (id: string | number) => `${API_BORROWS}${id}/`;
const API_BORROW_APPROVE = (id: string | number) =>
  `${API_BORROWS}${id}/approve/`;
const API_BORROW_REJECT = (id: string | number) =>
  `${API_BORROWS}${id}/reject/`;
const API_BORROW_CANCEL = (id: string | number) =>
  `${API_BORROWS}${id}/cancel/`;
const API_BORROW_HANDOVER = (id: string | number) =>
  `${API_BORROWS}${id}/handover/`;
const API_BORROW_RECEIVE_RETURN = (id: string | number) =>
  `${API_BORROWS}${id}/receive-return/`;
const API_BORROW_FINALIZE_RETURN = (id: string | number) =>
  `${API_BORROWS}${id}/finalize-return/`;
const API_BORROW_MARK_DAMAGED = (id: string | number) =>
  `${API_BORROWS}${id}/mark-damaged/`;
const API_BORROW_MARK_LOST = (id: string | number) =>
  `${API_BORROWS}${id}/mark-lost/`;
const API_BORROW_RETURN = (id: string | number) =>
  `${API_BORROWS}${id}/return/`;
const API_BORROW_REVIEW_CHECK = (id: string | number) =>
  `${API_BORROWS}${id}/review-check/`;
const API_BORROWS_BY_MONTH = `${API_BORROWS}by-month/`;


// REGION: Pengujians API Endpoints
const API_PENGUJIANS = `${API_BASE_URL}/pengujians/`;
const API_PENGUJIANS_MY = `${API_PENGUJIANS}my/`;
const API_PENGUJIANS_ALL = `${API_PENGUJIANS}all/`;
const API_PENGUJIANS_EXPORT = `${API_PENGUJIANS}all/export/`;
const API_PENGUJIANS_ALL_REQUESTERS = `${API_PENGUJIANS}all/requesters/`;
const API_PENGUJIAN_DOCUMENTS = `${API_PENGUJIANS}all/documents/`;
const API_PENGUJIANS_BULK_DELETE = `${API_PENGUJIANS}bulk-delete/`;
const API_PENGUJIAN_DETAIL = (id: string | number) =>
  `${API_PENGUJIANS}${id}/`;
const API_PENGUJIAN_APPROVE = (id: string | number) =>
  `${API_PENGUJIANS}${id}/approve/`;
const API_PENGUJIAN_REJECT = (id: string | number) =>
  `${API_PENGUJIANS}${id}/reject/`;
const API_PENGUJIAN_CANCEL = (id: string | number) =>
  `${API_PENGUJIANS}${id}/cancel/`;
const API_PENGUJIAN_COMPLETE = (id: string | number) =>
  `${API_PENGUJIANS}${id}/complete/`;
const API_PENGUJIAN_UPLOAD_DOCUMENT = (id: string | number) =>
  `${API_PENGUJIANS}${id}/documents/upload/`;

// REGION: Equipments API Endpoints
const API_EQUIPMENTS = `${API_BASE_URL}/equipments/`;
const API_EQUIPMENTS_DROPDOWN = `${API_EQUIPMENTS}dropdown/`;
const API_EQUIPMENTS_EXPORT = `${API_EQUIPMENTS}export/`;
const API_EQUIPMENTS_BULK_CREATE = `${API_EQUIPMENTS}bulk-create/`;
const API_EQUIPMENTS_BULK_DELETE = `${API_EQUIPMENTS}bulk-delete/`;
const API_EQUIPMENTS_BULK_SET_SHAREABLE = `${API_EQUIPMENTS}bulk-set-shareable/`;
const API_EQUIPMENTS_BULK_SET_BORROWABLE = `${API_EQUIPMENTS}bulk-set-borrowable/`;
const API_EQUIPMENT_DETAIL = (id: string | number) =>
  `${API_EQUIPMENTS}${id}/`;
const API_EQUIPMENT_AVAILABILITY = (id: string | number) =>
  `${API_EQUIPMENTS}${id}/availability/`;

const API_MATERIALS = `${API_BASE_URL}/materials/`;
const API_MATERIALS_DROPDOWN = `${API_MATERIALS}dropdown/`;
const API_MATERIALS_EXPORT = `${API_MATERIALS}export/`;
const API_MATERIALS_BULK_CREATE = `${API_MATERIALS}bulk-create/`;
const API_MATERIALS_BULK_DELETE = `${API_MATERIALS}bulk-delete/`;
const API_MATERIAL_DETAIL = (id: string | number) =>
  `${API_MATERIALS}${id}/`;

const API_SOFTWARES = `${API_BASE_URL}/softwares/`;
const API_SOFTWARES_EXPORT = `${API_SOFTWARES}export/`;
const API_SOFTWARES_BULK_CREATE = `${API_SOFTWARES}bulk-create/`;
const API_SOFTWARES_BULK_DELETE = `${API_SOFTWARES}bulk-delete/`;
const API_SOFTWARE_DETAIL = (id: string | number) =>
  `${API_SOFTWARES}${id}/`;

// REGION: Images API Endpoints
const API_IMAGES = `${API_BASE_URL}/images/`;
const API_IMAGE_DETAIL = (id: string | number) => `${API_IMAGES}${id}/`;

// REGION: Rooms API Endpoints
const API_ROOMS = `${API_BASE_URL}/rooms/`;
const API_ROOMS_DROPDOWN = `${API_ROOMS}dropdown/`;
const API_ROOMS_EXPORT = `${API_ROOMS}export/`;
const API_ROOMS_BULK_CREATE = `${API_ROOMS}bulk-create/`;
const API_ROOMS_BULK_DELETE = `${API_ROOMS}bulk-delete/`;
const API_ROOM_DETAIL = (id: string | number) => `${API_ROOMS}${id}/`;
const API_ROOM_AVAILABILITY = (id: string | number) =>
  `${API_ROOMS}${id}/availability/`;
const API_ANNOUNCEMENTS = `${API_BASE_URL}/announcements/`;
const API_ANNOUNCEMENTS_BULK_DELETE = `${API_ANNOUNCEMENTS}bulk-delete/`;
const API_SCHEDULES = `${API_BASE_URL}/schedules/`;
const API_SCHEDULE_FEED = `${API_SCHEDULES}feed/`;
const API_SCHEDULES_BULK_CREATE = `${API_SCHEDULES}bulk-create/`;
const API_SCHEDULES_BULK_DELETE = `${API_SCHEDULES}bulk-delete/`;
const API_SCHEDULE_DETAIL = (id: string | number) => `${API_SCHEDULES}${id}/`;
const API_CALENDAR = `${API_BASE_URL}/calendar/`;
const API_DASHBOARD_OVERVIEW = `${API_BASE_URL}/dashboard-overview/`;
const API_NOTIFICATIONS = `${API_BASE_URL}/notifications/`;
const API_FAQS = `${API_BASE_URL}/faqs/`;
const API_FAQS_BULK_DELETE = `${API_FAQS}bulk-delete/`;

export {
  API_BASE_URL,
  API_AUTH_BASE,
  API_ADMIN_BASE,
  API_AUTH_LOGIN,
  API_AUTH_LOGIN_ROUTE,
  API_AUTH_LOGOUT,
  API_AUTH_LOGIN_GOOGLE,
  API_AUTH_REGISTER,
  API_AUTH_VERIFY_EMAIL,
  API_AUTH_EMAIL_STATUS,
  API_AUTH_RESEND_VERIFICATION,
  API_AUTH_PASSWORD_RESET,
  API_AUTH_PASSWORD_RESET_CONFIRM,
  API_AUTH_PASSWORD_CHANGE,
  API_AUTH_USER,
  API_AUTH_USER_PROFILE,
  API_AUTH_MENTOR_USERS_DROPDOWN,
  API_AUTH_USER_PROFILE_DETAIL,
  API_AUTH_ADMIN_PROFILE,
  API_AUTH_ADMIN_PROFILE_DETAIL,
  API_AUTH_USERS,
  API_AUTH_USERS_EXPORT,
  API_AUTH_USERS_BULK_DELETE,
  API_AUTH_ASSIGNED_PIC_USERS_DROPDOWN,
  API_AUTH_PIC_USERS,
  API_AUTH_PIC_USERS_DROPDOWN,
  API_AUTH_PIC_USERS_BULK_REMOVE_ASSIGNMENTS,
  API_AUTH_PIC_USER_REMOVE_ASSIGNMENTS,
  API_AUTH_ADMIN_ACTIONS,
  API_AUTH_ADMIN_ACTIONS_RECENT,
  API_AUTH_ADMIN_ACTIONS_MY,
  API_AUTH_ADMIN_DASHBOARD,
  API_AUTH_ADMIN_DASHBOARD_KPIS,
  API_LAB_CLEARANCE,
  API_LAB_CLEARANCE_CHECK,
  API_AUTH_TOKEN_REFRESH,
  API_AUTH_TOKEN_VERIFY,
  API_BOOKINGS,
  API_BOOKINGS_MY,
  API_BOOKINGS_ALL,
  API_BOOKINGS_ALL_EXPORT,
  API_BOOKINGS_ALL_REQUESTERS,
  API_BOOKINGS_BULK_DELETE,
  API_BOOKING_DETAIL,
  API_BOOKING_APPROVE,
  API_BOOKING_REJECT,
  API_BOOKING_COMPLETE,
  API_BOOKING_CANCEL,
  API_BOOKING_REVIEW_CHECK,
  API_BOOKINGS_BY_MONTH,
  API_BORROWS,
  API_BORROWS_MY,
  API_BORROWS_ALL,
  API_BORROWS_EXPORT,
  API_BORROWS_ALL_REQUESTERS,
  API_BORROWS_BULK_DELETE,
  API_BORROW_DETAIL,
  API_BORROW_APPROVE,
  API_BORROW_REJECT,
  API_BORROW_CANCEL,
  API_BORROW_HANDOVER,
  API_BORROW_RECEIVE_RETURN,
  API_BORROW_FINALIZE_RETURN,
  API_BORROW_MARK_DAMAGED,
  API_BORROW_MARK_LOST,
  API_BORROW_RETURN,
  API_BORROW_REVIEW_CHECK,
  API_BORROWS_BY_MONTH,
  API_PENGUJIANS,
  API_PENGUJIANS_MY,
  API_PENGUJIANS_ALL,
  API_PENGUJIANS_EXPORT,
  API_PENGUJIANS_ALL_REQUESTERS,
  API_PENGUJIAN_DOCUMENTS,
  API_PENGUJIANS_BULK_DELETE,
  API_PENGUJIAN_DETAIL,
  API_PENGUJIAN_APPROVE,
  API_PENGUJIAN_REJECT,
  API_PENGUJIAN_CANCEL,
  API_PENGUJIAN_COMPLETE,
  API_PENGUJIAN_UPLOAD_DOCUMENT,
  API_EQUIPMENTS,
  API_EQUIPMENTS_DROPDOWN,
  API_EQUIPMENTS_EXPORT,
  API_EQUIPMENTS_BULK_CREATE,
  API_EQUIPMENTS_BULK_DELETE,
  API_EQUIPMENTS_BULK_SET_SHAREABLE,
  API_EQUIPMENTS_BULK_SET_BORROWABLE,
  API_EQUIPMENT_DETAIL,
  API_EQUIPMENT_AVAILABILITY,
  API_MATERIALS,
  API_MATERIALS_DROPDOWN,
  API_MATERIALS_EXPORT,
  API_MATERIALS_BULK_CREATE,
  API_MATERIALS_BULK_DELETE,
  API_MATERIAL_DETAIL,
  API_SOFTWARES,
  API_SOFTWARES_EXPORT,
  API_SOFTWARES_BULK_CREATE,
  API_SOFTWARES_BULK_DELETE,
  API_SOFTWARE_DETAIL,
  API_IMAGES,
  API_IMAGE_DETAIL,
  API_ROOMS,
  API_ROOMS_DROPDOWN,
  API_ROOMS_EXPORT,
  API_ROOMS_BULK_CREATE,
  API_ROOMS_BULK_DELETE,
  API_ROOM_DETAIL,
  API_ROOM_AVAILABILITY,
  API_ANNOUNCEMENTS,
  API_ANNOUNCEMENTS_BULK_DELETE,
  API_SCHEDULES,
  API_SCHEDULE_FEED,
  API_SCHEDULES_BULK_CREATE,
  API_SCHEDULES_BULK_DELETE,
  API_SCHEDULE_DETAIL,
  API_CALENDAR,
  API_DASHBOARD_OVERVIEW,
  API_NOTIFICATIONS,
  API_FAQS,
  API_FAQS_BULK_DELETE,
};
