# Generated by Django 4.2.27 on 2026-04-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0031_alter_pengujian_status_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_shareable',
            field=models.BooleanField(default=False),
        ),
    ]
