# Generated by Django 4.2.27 on 2026-04-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0032_equipment_is_shareable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Under Maintenance', 'Under Maintenance'), ('Broken', 'Broken'), ('In Storage', 'In Storage')], default='Available', max_length=20),
        ),
    ]
