# Generated by Django 4.2.27 on 2026-04-15 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0033_remove_equipment_image_remove_room_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Storage', 'In Storage'), ('Consumed', 'Consumed'), ('Expired', 'Expired')], default='Available', max_length=20)),
                ('category', models.CharField(choices=[('Chemicals', 'Chemicals'), ('Biological Materials', 'Biological Materials'), ('Consumables', 'Consumables'), ('Other', 'Other')], default='Other', max_length=20)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='csluse.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
