# Generated by Django 4.2.27 on 2026-04-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0034_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_borrowable',
            field=models.BooleanField(default=False),
        ),
    ]
