# Generated by Django 4.2.27 on 2026-04-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0009_profile_is_mentor'),
        ('csluse', '0035_equipment_is_borrowable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='csluse_auth.profile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='csluse.room'),
        ),
        migrations.AlterField(
            model_name='bookingequipmentitem',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='csluse.equipment'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrows', to='csluse.equipment'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrows', to='csluse_auth.profile'),
        ),
        migrations.AlterField(
            model_name='pengujian',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengujians', to='csluse_auth.profile'),
        ),
        migrations.AlterField(
            model_name='use',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uses', to='csluse.equipment'),
        ),
        migrations.AlterField(
            model_name='use',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uses', to='csluse_auth.profile'),
        ),
    ]
