# Generated by Django 4.2.27 on 2026-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0036_alter_booking_requested_by_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_useable',
            field=models.BooleanField(default=True),
        ),
    ]
