# Generated by Django 4.2.27 on 2026-04-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0038_alter_equipment_is_useable_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='is_useable',
        ),
        migrations.DeleteModel(
            name='Use',
        ),
    ]
