# Generated by Django 4.2.27 on 2026-04-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csluse", "0039_remove_use_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("testing_agreement", "Surat perjanjian pengujian"),
                    (
                        "signed_testing_agreement",
                        "Surat perjanjian pengujian yang sudah ditandatangani",
                    ),
                    ("invoice", "Invoice"),
                    ("payment_proof", "Bukti bayar"),
                    ("receipt", "Kuitansi"),
                    ("test_result_letter", "Surat hasil uji"),
                ],
                max_length=64,
            ),
        ),
    ]
