# Generated by Django 4.2.27 on 2026-04-21 02:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csluse_auth', '0009_profile_is_mentor'),
        ('csluse', '0041_alter_booking_borrow_pengujian_status_add_canceled'),
    ]

    operations = [
        # 1. Buat model SuratBebasLab (tanpa FK dulu)
        migrations.CreateModel(
            name='SuratBebasLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=12, null=True, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        # 2. Tambah FK ke SuratBebasLab
        migrations.AddField(
            model_name='suratbebaslab',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surat_bebas_lab_requests', to='csluse_auth.profile'),
        ),
        migrations.AddField(
            model_name='suratbebaslab',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_bebas_lab_reviews', to='csluse_auth.profile'),
        ),
        # 3. Update Document: hapus constraint lama, ubah field
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_pengujian_document_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('testing_agreement', 'Surat perjanjian pengujian'), ('signed_testing_agreement', 'Surat perjanjian pengujian yang sudah ditandatangani'), ('invoice', 'Invoice'), ('payment_proof', 'Bukti bayar'), ('receipt', 'Kuitansi'), ('test_result_letter', 'Surat hasil uji'), ('form_alat_kecil', 'F-027A Peminjaman dan Pengembalian Alat Kecil'), ('form_alat_besar', 'F-027B Pemakaian Alat Besar'), ('form_permintaan_bahan', 'F-028 Permintaan Bahan')], max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='pengujian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='csluse.pengujian'),
        ),
        # 4. Tambah FK surat_bebas_lab ke Document SEBELUM constraint
        migrations.AddField(
            model_name='document',
            name='surat_bebas_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='csluse.suratbebaslab'),
        ),
        # 5. Tambah constraints setelah semua field ada
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('pengujian__isnull', False)), fields=('pengujian', 'document_type'), name='unique_pengujian_document_type'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('surat_bebas_lab__isnull', False)), fields=('surat_bebas_lab', 'document_type'), name='unique_surat_bebas_lab_document_type'),
        ),
    ]
