# Generated by Django 4.2.27 on 2026-04-21 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csluse', '0043_remove_pengujian_waiting_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratBebasLabBookingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_room_name', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('surat_bebas_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_histories', to='csluse.suratbebaslab')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
