# Generated by Django 4.2.27 on 2026-04-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("csluse", "0044_suratbebaslabbookinghistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suratbebaslabbookinghistory",
            name="purpose",
        ),
    ]
