# Generated by Django 4.2.27 on 2026-04-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("csluse", "0045_remove_suratbebaslabbookinghistory_purpose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="image",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="created_by",
        ),
    ]
