# Generated by Django 4.2.27 on 2026-04-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("csluse", "0046_remove_image_schedule_faq_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingequipmentitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="bookingequipmentitem",
            name="updated_at",
        ),
    ]
