# Generated by Codex on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csluse", "0051_borrow_repaired_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
