events {}

http {
  resolver 127.0.0.11 valid=10s;

  upstream frontend_upstream {
    server frontend:80;
  }

  upstream backend_upstream {
    server backend:8000;
  }

  server {
    listen 80;
    server_name csl-test.azizrahmad.com;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name csl-test.azizrahmad.com;

    ssl_certificate /etc/letsencrypt/live/csl-test.azizrahmad.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/csl-test.azizrahmad.com/privkey.pem;

    location / {
      proxy_pass http://frontend_upstream;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
      proxy_pass http://backend_upstream;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
